modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#主页ID
displayURL="https://www.mcmod.cn/class/1077.html"
#待制
logoFile="negorerouse.png"
authors="${mod_authors}"

description='''
若你敢握住它们，便已踏入永夜秘境。
“光明易朽，曈光永恒。”
If you dare to grasp them, you step into the eternal night’s realm.
"Light fades easily, but twilight endures forever."
'''
#拔刀剑：重锋(前置)
[[dependencies.${mod_id}]]
    modId="slashblade"
    mandatory=true
    versionRange="[1.1.11,)"
    ordering="NONE"
    side="BOTH"
#光子
[[dependencies.${mod_id}]]
    modId="photon"
    mandatory=true
    versionRange="[1.1.0,)"
    ordering="NONE"
    side="BOTH"
#饰品
[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    versionRange="[5.11.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"